rules:
  line-length:
    max: 100
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  document-start: disable
  document-end: disable