services:
  web:
    build: .
    ports:
      - "8001:8000" # Changed host port to 8001 to avoid conflict
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/dndstory
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    working_dir: /app

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dndstory
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dndstory"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5432:5432"



volumes:
  postgres_data: